# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d0f63ede8a09a456eedc0ea4fe440451cb9b0d3716cb414b02f7517053f50f90154aa1d93fdedf463830bfa08f05ab8af5258466324446ce4459c481ea2802d

test:
  secret_key_base: f5152d161e35bea136d7c63c7ec5d9b23577b2922706b0eadbb380f27663e9abde15d00efba5a01cb1195a32d344866ec2b2064ad3fb194e18ff9bf8b80532a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
